name: Supabase Scheduled Job

on:
  schedule:
    - cron: '0 1 */5 * *'  # Mỗi 5 ngày lúc 08:00 GMT+7 (tức 01:00 UTC)
  workflow_dispatch:

jobs:
  run-supabase:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_REF:           ${{ secrets.PROJECT_REF }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify Supabase CLI
        run: supabase --version

      - name: Supabase login
        run: supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Dump database (ví dụ)
        run: supabase db dump --project-ref $PROJECT_REF --file=backup.sql
