name: Supabase CLI - Scheduled Run

on:
  schedule:
    - cron: '0 1 */5 * *'  # 01:00 UTC tương đương 08:00 GMT+7
  workflow_dispatch:       # Cho phép chạy thủ công nếu cần

jobs:
  run-supabase-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

- name: Install Supabase CLI
  run: |
    SUPABASE_VERSION=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    curl -sL "https://github.com/supabase/cli/releases/download/v${SUPABASE_VERSION}/supabase_${SUPABASE_VERSION}_linux_amd64.tar.gz" -o supabase.tar.gz
    tar -xzf supabase.tar.gz supabase
    chmod +x supabase
    sudo mv supabase /usr/local/bin/supabase


      - name: Verify Supabase CLI
        run: supabase --version

      - name: Authenticate with Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          mkdir -p ~/.supabase
          echo "[global]" > ~/.supabase/config.toml
          echo "access_token = \"$SUPABASE_ACCESS_TOKEN\"" >> ~/.supabase/config.toml

      - name: Run Supabase command (example)
        run: |
          supabase db dump --file=backup.sql
          echo "Dumped database to backup.sql"

      # Optional: Gửi file backup.sql qua email, S3, GDrive, v.v...
